trigger:
  branches:
    include:
    - master
  paths:
    include:
    - AZ_rg-Sales-DevQA-Q01_Solution/VMSqlResources/Pipelines/deploy-pipelines.yml

pr: none

stages:
- stage: 
  jobs:
  - job: job_Network
    steps:
    - template: ../PipelineTemplates/deploy-arm-template-02.yml
      parameters:
        parameterfilename: "CAPAZISQLC01.parameters.json"
        templatefilename: "virtual_machine_NICs.v2.3.deploy.json"
  - job: job_Virtual_Machine
    dependsOn: job_Network
    condition: succeeded()
    steps:
    - template: ../PipelineTemplates/deploy-arm-template-02.yml
      parameters:
        parameterfilename: "CAPAZISQLC01.parameters.json"
        templatefilename: "virtual_machine.v2.2.deploy.json"
  - job: job_Install_SQL_Server
    dependsOn: job_Virtual_Machine
    condition: succeeded()
    steps:
    - template: ../PipelineTemplates/deploy-arm-template-02.yml
      parameters:
        parameterfilename: "CAPAZISQLC01.parameters.json"
        templatefilename: "virtual_machine_win_script.v2.2.deploy.json"
  - job: job_Restore_SQL_DB
    dependsOn: job_Install_SQL_Server
    condition: succeeded()
    steps:
    - script: echo 'Restore adventure-works-2008r2-oltp'
